// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { handleEdgeFunction } from '@/server/functionsRouter';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL =
  typeof rawUrl === 'string' && rawUrl.trim().startsWith('http')
    ? rawUrl.trim()
    : 'https://qhlunszfcpzsfjjugkus.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  typeof rawKey === 'string' && rawKey.trim().length > 0
    ? rawKey.trim()
    : 'sb_publishable_xp0FiNgyQFvsdy9SXeGnSA_iUehC_FO';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage() || localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Proxy supabase.functions.invoke: prefer real Supabase Edge Function API, fallback to local functionsRouter
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);

supabase.functions.invoke = async function (functionName: string, options?: any) {
  // 1. Try real Supabase Edge Function execution first
  try {
    const res = await originalInvoke(functionName, options);
    if (res && (!res.error || !String(res.error.message || res.error).includes("Failed to send a request"))) {
      if (res.data) {
        return res;
      }
    }
  } catch (invokeErr: any) {
    console.warn(`[EdgeFunction:${functionName}] Chamada remota indisponível, usando roteador local:`, invokeErr?.message);
  }

  // 2. Fallback to local server functionsRouter execution
  try {
    const session = (await supabase.auth.getSession()).data?.session;
    const authHeader = session?.access_token ? `Bearer ${session.access_token}` : undefined;
    const result = await handleEdgeFunction(functionName, options?.body || {}, authHeader);

    if (result && typeof result.status === "number") {
      return { data: result.body, error: null };
    }
  } catch (routerErr: any) {
    console.warn(`[EdgeFunction:${functionName}] Erro no roteador local:`, routerErr);
  }

  return {
    data: {
      success: false,
      edge_function_ok: false,
      code: "ERRO_CONEXAO",
      message: `Não foi possível comunicar com a Edge Function ${functionName}.`,
    },
    error: { message: `Não foi possível comunicar com a Edge Function ${functionName}.` },
  };
};
