// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// URL validation: must be a valid HTTP/HTTPS URL and not point to old database hosts
const SUPABASE_URL = (
  typeof rawUrl === 'string' &&
  rawUrl.startsWith('http') &&
  !rawUrl.includes('lxgnttjzhqbpmnrpkvjw') &&
  !rawUrl.includes('xnmrbsqhhjtqmgixjalw')
)
  ? rawUrl.trim()
  : "https://qhlunszfcpzsfjjugkus.supabase.co";

// Key validation: ignore keys from old or mismatched Supabase projects that trigger "Invalid API key"
const isMismatchedKey = (key?: unknown): boolean => {
  if (typeof key !== 'string') return true;
  const trimmed = key.trim();
  return (
    trimmed.length === 0 ||
    trimmed.includes('U-J_S8DnJK5K') || // old lxgnttjzhqbpmnrpkvjw key
    trimmed.includes('MCZh1FNBp8oYd8iL') || // old xnmrbsqhhjtqmgixjalw key
    trimmed.includes('placeholder')
  );
};

const SUPABASE_PUBLISHABLE_KEY = (!isMismatchedKey(rawKey))
  ? (rawKey as string).trim()
  : "sb_publishable_xp0FiNgyQFvsdy9SXeGnSA_iUehC_FO";

// Clean up stale auth token from old database projects if present to avoid auth mismatch
try {
  const currentProjTokenKey = "sb-qhlunszfcpzsfjjugkus-auth-token";
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key && key.startsWith("sb-") && key.endsWith("-auth-token") && key !== currentProjTokenKey) {
      localStorage.removeItem(key);
    }
  }
} catch {}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Configure functions invocation to use the application server endpoints without CORS or 404 issues
if (typeof window !== "undefined") {
  try {
    const origInvoke = supabase.functions.invoke.bind(supabase.functions);
    supabase.functions.invoke = async (functionName: string, options: any = {}) => {
      try {
        const session = (await supabase.auth.getSession()).data.session;
        const headers: Record<string, string> = {
          "Content-Type": "application/json",
          ...(options.headers || {}),
        };
        if (session?.access_token) {
          headers["Authorization"] = `Bearer ${session.access_token}`;
        }
        if (SUPABASE_PUBLISHABLE_KEY) {
          headers["apikey"] = SUPABASE_PUBLISHABLE_KEY;
        }

        const localUrl = `${window.location.origin}/functions/v1/${functionName}`;
        const res = await fetch(localUrl, {
          method: options.method || "POST",
          headers,
          body: options.body ? JSON.stringify(options.body) : undefined,
        });

        if (res.ok) {
          const data = await res.json().catch(() => ({}));
          return { data, error: null };
        }

        // If local returned a non-OK status, extract JSON or error text
        const errJson = await res.json().catch(() => null);
        if (errJson) {
          return { data: errJson, error: new Error(errJson.message || errJson.error || `HTTP ${res.status}`) };
        }

        return { data: null, error: new Error(`Erro ao chamar a Edge Function (${res.status})`) };
      } catch (err: any) {
        console.warn(`[functions.invoke] Local dispatch error for ${functionName}:`, err);
        // Fallback to original invoke
        try {
          return await origInvoke(functionName, options);
        } catch (origErr: any) {
          return {
            data: { success: false, code: "ERRO_CONEXAO", message: origErr.message || "Erro de conexão com a função." },
            error: origErr,
          };
        }
      }
    };
  } catch (e) {
    console.warn("Could not enhance supabase.functions.invoke", e);
  }
}
