// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { handleEdgeFunction } from '@/server/functionsRouter';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL =
  typeof rawUrl === 'string' && rawUrl.trim().startsWith('http')
    ? rawUrl.trim()
    : 'https://qhlunszfcpzsfjjugkus.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  typeof rawKey === 'string' && rawKey.trim().length > 0
    ? rawKey.trim()
    : 'sb_publishable_xp0FiNgyQFvsdy9SXeGnSA_iUehC_FO';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage() || localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Proxy supabase.functions.invoke to backend /functions/v1/* endpoint or in-browser fallback
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = async function (functionName: string, options?: any) {
  try {
    const session = (await supabase.auth.getSession()).data?.session;
    const authHeader = session?.access_token ? `Bearer ${session.access_token}` : undefined;
    const res = await fetch(`/functions/v1/${functionName}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(authHeader ? { Authorization: authHeader } : {}),
        ...(options?.headers || {}),
      },
      body: options?.body ? JSON.stringify(options.body) : JSON.stringify({}),
    });
    if (res.ok) {
      const data = await res.json().catch(() => null);
      return { data, error: null };
    }
  } catch (fetchErr) {
    console.warn(`[EdgeFunction:${functionName}] HTTP fetch indisponível, executando fallback local.`, fetchErr);
  }

  // Robust fallback: Execute local functionsRouter without raw Edge Function failure
  try {
    const session = (await supabase.auth.getSession()).data?.session;
    const authHeader = session?.access_token ? `Bearer ${session.access_token}` : undefined;
    const result = await handleEdgeFunction(functionName, options?.body || {}, authHeader);
    
    if (result.status >= 200 && result.status < 300) {
      return { data: result.body, error: null };
    }
    return {
      data: null,
      error: { message: result.body?.error || result.body?.message || `HTTP ${result.status}` },
    };
  } catch (routerErr: any) {
    console.warn(`[EdgeFunction:${functionName}] Erro no roteador local, chamando SDK original:`, routerErr);
    try {
      return await originalInvoke(functionName, options);
    } catch (invokeErr: any) {
      return {
        data: null,
        error: { message: invokeErr?.message || "Falha ao enviar requisição." },
      };
    }
  }
};
